#! /usr/bin/env python3
# ------------------
# Sample xml file
# ------------------
# <background>
#
# <starttime>
#   <year>2017</year>
#   <month>08</month>
#   <day>23</day>
#   <hour>13</hour>
#   <minute>51</minute>
#   <second>55</second>
# </starttime>
#
# <static>
#   <duration>5760.0</duration>
#   <!-- how long to show the picture -->
#   <file>/home/moon1.jpg</file>
# </static>
# <transition type='overlay'>
#   <duration>5760.0</duration>
#   <from>/home/moon1.jpg</from>
#   <to>/home/moon2.jpg</to>
# </transition>
# <static>
#   <duration>5760.0</duration>
#   <file>/home/moon2.jpg</file>
# </static>
#
# </background>
# ------------------

import argparse
import os
import datetime
import random
import xml.etree.ElementTree as ET

class AutoBackground():
    # Class to generate the xml file
    def __init__(self,
                 figpath,
                 transition=None,
                 randomtime=True,
                 duration=None):
        self.figpath = figpath
        self.starttime = datetime.datetime.now()
        self.xml = dict()
        self.xml['background'] = ET.Element('background')
        self.__xmlstarttime()
        self.transition = self.__transition(transition)
        self.duration = self.__duration(randomtime, duration)
        self.__xmlfigpath()
        self.et = ET.ElementTree(self.xml['background'])

    def getet(self):
        # return the ElementTree
        return self.et

    def __xmlstarttime(self):
        # make the start time block
        self.xml['starttime'] = ET.SubElement(
            self.xml['background'], 'starttime'
        )
        for timename in [
                'year', 'month', 'day', 'hour', 'minute', 'second'
        ]:
            self.xml[
                '_'.join(['starttime', timename])
            ] = ET.SubElement(
                self.xml['starttime'], timename
            )
            self.xml[
                '_'.join(['starttime', timename])
            ].text = '{0:02}'.format(
                getattr(self.starttime, timename)
            )

    def __transition(self, transition):
        if not isinstance(transition, list):
            # transition with only one value
            result = [
                'static' for i in range(len(self.figpath))
            ]
        else:
            # transition gaven as a list
            transition = [x for x in transition if x != 'static']
            if len(self.figpath) - 1 > len(transition):
                transition = transition * (
                    len(self.figpath) - 1 // len(transition)
                )
            else:
                pass
            result = ['static'] * (len(self.figpath) * 2 -1)
            for i in range(len(self.figpath) * 2 - 1):
                if i % 2 == 1:
                    result[i] = transition[(i-1) // 2]
                else:
                    pass
        return result

    def __duration(self, randomtime, duration):
        # generate duration time list
        if isinstance(duration, list):
            # get the time from input
            if len(duration) == len(self.transition):
                 result = [str(x) for x in duration]
            else:
                for i in range(
                        len(self.transition) // len(duration) + 1
                ):
                    duration += duration
                result = [
                    str(duration[i]) for i in range(len(self.transition))
                ]
        elif isinstance(duration, float) or isinstance(duration, int):
            # expand one time input to the length of figure list
            result = [
                str(duration) for i in range(len(self.transition))
            ]
        elif randomtime:
            #  generate random time
            result = [
                str(random.randint(15 * 60, 120 * 60))
                for i in range(len(self.transition))
            ]
        else:
            # generate averaged duration time
            result = [
                str(round(86400 / len(self.transition), 2))
                for i in range(len(self.transition))
            ]
        return result

    def __xmlfigpath(self):
        # make the picture block acording to the transition option
        # default is static
        if len(self.transition) == len(self.figpath):
            # all the figure is static
            for i in range(len(self.transition)):
                self.xml['_'.join(['fig', str(i)])] = ET.SubElement(
                    self.xml['background'], 'static'
                )
                ET.SubElement(
                    self.xml['_'.join(['fig', str(i)])], 'duration'
                ).text = self.duration[i]
                ET.SubElement(
                    self.xml['_'.join(['fig', str(i)])], 'file'
                ).text = self.figpath[i]
        else:
            # figures have transition
            for i in range(len(self.transition)):
                if self.transition[i] == 'static':
                    self.xml['_'.join(['fig', str(i)])] = ET.SubElement(
                        self.xml['background'], 'static'
                    )
                    ET.SubElement(
                        self.xml['_'.join(['fig', str(i)])], 'duration'
                    ).text = self.duration[i]
                    ET.SubElement(
                        self.xml['_'.join(['fig', str(i)])], 'file'
                    ).text = self.figpath[i // 2]
                else:
                    self.xml['_'.join(['fig', str(i)])] = ET.SubElement(
                        self.xml['background'], 'transition',
                        attrib={'type': self.transition[i]}
                    )
                    ET.SubElement(
                        self.xml['_'.join(['fig', str(i)])], 'duration'
                    ).text = self.duration[i]
                    ET.SubElement(
                        self.xml['_'.join(['fig', str(i)])], 'from'
                    ).text = self.figpath[(i - 1) // 2]
                    ET.SubElement(
                        self.xml['_'.join(['fig', str(i)])], 'to'
                    ).text = self.figpath[(i + 1) // 2]



if __name__ == '__main__':
    # parse arguments
    parser = argparse.ArgumentParser(
        prog='autobackground',
        description='Make auto change background of gnome desktop'
    )
    parser.add_argument(
        'figname',
        action='store',
        nargs='*',
        default=None,
        help='an integer for the accumulator'
    )
    parser.add_argument(
        '-d', '--figure-directory',
        action='store',
        default=os.getcwd(),
        help='The directory to store all the background figures.'
    )
    parser.add_argument(
        '-o', '--output',
        action='store',
        default='bg.xml',
        help='The output xml file name.'
    )
    parser.add_argument(
        '-wd', '--working-directory',
        action='store',
        default=os.getcwd(),
        help='The working directory, where is the default place to save xml file.'
    )
    parser.add_argument(
        '-t', '--duration-time',
        nargs='*',
        action='store',
        default=None,
        help='Duration time for each background.'
    )
    parser.add_argument(
        '-r', '--random-time',
        action='store_true',
        default=False,
        help='Set duration time to random time.'
    )
    parser.add_argument(
        '-x', '--transition',
        action='store',
        nargs='*',
        default=None,
        choices=['static', 'overlay'],
        help='Set duration time to random time.'
    )

    args = parser.parse_args()

    figdir = os.path.abspath(args.figure_directory)
    if not args.figname:
        figname = os.listdir(figdir)
    else:
        figname = args.figname

    if not os.path.dirname(figname[0]):
        figname = [
            os.path.join(figdir, x)
            for x in figname
        ]
    else:
        figname = [os.path.abspath(x) for x in figname]

    if not os.path.dirname(args.output):
        outfile = os.path.join(args.working_directory, args.output)
    else:
        outfile = os.path.abspath(args.output)

    bg = AutoBackground(
        figpath=figname,
        transition=args.transition,
        randomtime=args.random_time,
        duration=args.duration_time
    )

    et = bg.getet()
    et.write(outfile)
    print('Output xml file: ' + outfile)
else:
    pass
